# Generated by Django 4.2 on 2023-04-21 22:44

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import job.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full time', 'Permanent'), ('Part time', 'Parttime'), ('Internship', 'Internship'), ('Freelance', 'Freelance'), ('Temporary', 'Temporary'), ('Contract', 'Contract'), ('Volunteer', 'Volunteer')], default='Full time', max_length=100)),
                ('education', models.CharField(choices=[('Bachelors', 'Bachelors'), ('Masters', 'Masters'), ('Doctorate', 'Doctorate'), ('Post Doctorate', 'Postdoctorate')], default='Bachelors', max_length=100)),
                ('experience', models.CharField(choices=[('No Experience', 'No Experience'), ('1 Year', 'One Year'), ('2 Years', 'Two Years'), ('3 Years', 'Three Years'), ('4 Years', 'Four Years'), ('5 Years or more', 'Five Years')], default='No Experience', max_length=100)),
                ('industry', models.CharField(choices=[('Bussiness', 'Bussiness'), ('Information Technology', 'Information Technology'), ('Education', 'Education'), ('Health Care', 'Health Care'), ('Finance', 'Finance'), ('Construction', 'Construction'), ('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Transportation', 'Transportation'), ('Retail', 'Retail'), ('Media', 'Media'), ('Government', 'Government'), ('Hospitality', 'Hospitality'), ('Telecommunication', 'Telecommunication'), ('Other', 'Other')], default='Other', max_length=100)),
                ('salary', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('positions', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000)])),
                ('company', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateTimeField(default=job.models.return_date_time)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0.0, 0.0), null=True, srid=4326)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
